// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'http://localhost:54321';
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprdWFmbWlydGpzZ2hrZWJramJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMzEyOTAsImV4cCI6MjA1NTgwNzI5MH0.cVT2_yv7CC7MF0_3WEIFVSDHMxdKYJ-Qgz43mZFptVg';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);
